# Generated by Django 2.2.1 on 2019-05-07 14:29

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('odev', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2019, 5, 7, 14, 29, 41, 147820, tzinfo=utc)),
        ),
    ]
